---
- hosts: bb-app-prd
  gather_facts: no
  become: yes
  become_user: root
  become_method: su
  remote_user:  root
  tasks:
  - lineinfile:
        path: /etc/security/limits.conf
        regexp: 'End of file'
        line: '* hard nofile 65536'
