--- # this is a controll for bb-app-dev
- hosts: all
  remote_user: ansible
  become : yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars:
    username: bbuser
            
  tasks:
  - name: mount CDROM
    mount :
      path: /mnt/dvd
      src: /dev/sr0
      fstype: iso9660
      opts: ro,noauto
      state: mounted
  - name: install ntp
    template : src=ntp.conf dest=/etc/ntp.conf
    notify:
       - restart ntp
  handlers:
   - name: restart ntp
     service: name=ntpd state=restarted
